# MS-CAT 掩蔽预训练配置文件

# 随机种子
seed: 42

# 数据配置
data:
  data_path: "data/AMPds2.h5"
  window_size: 240  # 窗口大小（分钟）
  overlap: 120      # 重叠大小（分钟）
  batch_size: 32
  num_workers: 8
  pin_memory: true
  
  # 特征配置
  features:
    # 基础通道
    base_channels: ["P_total", "Q_total", "S_total", "I", "V", "PF"]
    
    # 派生特征
    derived_features:
      enable_delta: true           # 一阶差分
      enable_rolling_stats: true   # 滑窗统计
      enable_energy: true          # 窗口能量
      enable_frequency: true       # 简易频域特征
      enable_time_features: true   # 时间特征
    
    # 滑窗统计参数
    rolling_windows: [3, 5, 10]   # 滑窗大小（分钟）
    
    # 频域特征参数
    frequency_bands: 3            # 频带数量
    
  # 归一化
  normalization:
    method: "robust"              # robust, standard, minmax
    per_channel: true
  
  # 数据增强
  augmentation:
    enable: true
    noise_std: 0.02              # 加性噪声标准差
    amplitude_range: [0.9, 1.1]  # 幅度缩放范围
    channel_dropout: 0.1         # 通道dropout概率
    time_jitter: 2               # 时间抖动（分钟）

# 模型配置
model:
  # 基础架构参数
  d_model: 192
  num_heads: 6
  local_layers: 4
  global_layers: 3
  
  # 注意力参数
  window_size: 32              # 局部注意力窗口大小
  sparsity_factor: 4           # 稀疏注意力因子
  
  # 卷积参数
  conv_kernel_size: 7
  
  # 融合策略
  fusion_type: "weighted_sum"   # weighted_sum, concat, attention
  
  # 位置编码
  use_time_features: true
  learnable_pos: false         # 是否使用可学习位置编码
  
  # 正则化
  dropout: 0.1
  max_len: 5000
  
  # 掩蔽策略
  mask_ratio: 0.25             # 掩蔽比例
  mask_strategy: "random"       # random, block, channel
  
  # 优化器参数
  learning_rate: 1e-3
  weight_decay: 1e-4
  warmup_steps: 1000
  max_steps: 50000
  
  # 一致性正则化
  consistency_weight: 0.1

# 训练参数
training:
  max_epochs: 100
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  check_val_every_n_epoch: 1
  enable_progress_bar: true
  enable_model_summary: true
  deterministic: false
  benchmark: true

# 优化器
optimizer:
  name: "AdamW"
  lr: 1e-3
  weight_decay: 1e-4
  betas: [0.9, 0.999]
  eps: 1e-8

# 学习率调度
scheduler:
  name: "CosineAnnealingLR"
  T_max: 100
  eta_min: 1e-6
  warmup_epochs: 10
  warmup_start_lr: 1e-6

# 验证
validation:
  val_check_interval: 0.5
  limit_val_batches: 100

# 检查点
checkpoint:
  monitor: "val/reconstruction_loss"
  mode: "min"
  save_top_k: 3
  save_last: true
  filename: "mscat_pretrain_{epoch:02d}_{val_reconstruction_loss:.4f}"

# 早停
early_stopping:
  monitor: "val/reconstruction_loss"
  patience: 15
  mode: "min"
  min_delta: 1e-4

# 日志
logging:
  name: "mscat_pretrain"
  save_dir: "outputs/pretrain"
  log_every_n_steps: 50

# 硬件
hardware:
  accelerator: "gpu"
  devices: 1
  precision: 16
  strategy: "auto"