# 默认配置文件

# 数据配置
data:
  data_path: "data/AMPds2.h5"  # 数据文件路径
  sequence_length: 512  # 序列长度
  train_ratio: 0.8  # 训练集比例
  max_samples: 50000  # 最大样本数
  batch_size: 32  # 批次大小
  num_workers: 4  # 数据加载器工作进程数
  appliances:  # 设备列表
    - "fridge"
    - "washer_dryer"
    - "microwave"
    - "dishwasher"

# 模型配置
model:
  input_dim: 1  # 输入维度
  d_model: 256  # 模型维度
  n_heads: 8  # 注意力头数
  n_layers: 6  # Transformer层数
  d_ff: 1024  # 前馈网络维度
  dropout: 0.1  # Dropout率
  num_appliances: 4  # 设备数量
  window_size: 64  # 窗口大小

# 损失函数配置
loss:
  power_weight: 1.0  # 功率损失权重
  state_weight: 0.5  # 状态损失权重
  correlation_weight: 0.3  # 相关性损失权重

# 训练配置
training:
  learning_rate: 1e-4  # 学习率
  max_epochs: 100  # 最大训练轮数
  patience: 10  # 早停耐心值
  min_delta: 1e-4  # 早停最小改进
  gradient_clip_val: 1.0  # 梯度裁剪值
  accumulate_grad_batches: 1  # 梯度累积批次
  precision: 32  # 训练精度
  
# 验证配置
validation:
  val_check_interval: 1.0  # 验证检查间隔
  check_val_every_n_epoch: 1  # 每N个epoch验证一次

# 日志配置
logging:
  log_every_n_steps: 50  # 每N步记录一次日志
  save_dir: "outputs/logs"  # 日志保存目录
  name: "enhanced_transformer_nilm"  # 实验名称
  version: null  # 版本号（自动生成）

# 检查点配置
checkpoint:
  save_dir: "outputs/checkpoints"  # 检查点保存目录
  filename: "enhanced_transformer_nilm-{epoch:02d}-{val_loss:.2f}"  # 文件名格式
  monitor: "val_loss"  # 监控指标
  mode: "min"  # 监控模式
  save_top_k: 3  # 保存最好的K个模型
  save_last: true  # 保存最后一个模型
  every_n_epochs: 1  # 每N个epoch保存一次

# 输出配置
output:
  results_dir: "outputs/results"  # 结果保存目录
  visualizations_dir: "outputs/visualizations"  # 可视化保存目录
  save_predictions: true  # 是否保存预测结果
  save_metrics: true  # 是否保存评估指标

# 设备配置
device:
  accelerator: "auto"  # 加速器类型（auto, cpu, gpu, tpu）
  devices: "auto"  # 设备数量
  strategy: "auto"  # 训练策略

# 随机种子
seed: 42